version: '2'
services:

  stack_a2sapi-nginx:
    container_name: stack_a2sapi-nginx
    image: nginx:1.13-alpine
    labels:
      - "stack=a2sapi"
      - "container=nginx"
    ports:
      - 80:80
    volumes:
      - ./stack_a2sapi-nginx/.docker/nginx/html/swagger.yaml:/usr/share/nginx/html/swagger.yaml:ro
      - ./stack_a2sapi-nginx/.docker/nginx/conf/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./stack_a2sapi-nginx/.docker/nginx/conf/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro

  stack_a2sapi-a2sapi:
    container_name: stack_a2sapi-a2sapi
    build:
      context: stack_a2sapi-a2sapi
    labels:
      - "stack=a2sapi"
      - "container=a2sapi"

  stack_a2sapi-swagger:
    container_name: stack_a2sapi-swagger
    image: swaggerapi/swagger-ui:v3.14.2
    labels:
      - "stack=a2sapi"
      - "container=swagger"
    environment:
      - API_URL=swagger.yaml